# Radon Shell – Zsh-Grundkonfiguration
autoload -Uz compinit && compinit
setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS
setopt AUTO_CD
setopt INTERACTIVE_COMMENTS

export EDITOR="${EDITOR:-nano}"
export VISUAL="${VISUAL:-$EDITOR}"

alias ll='ls -lah'
alias la='ls -A'
alias l='ls -CF'
alias radon-update='radon update'
alias radon-status='radon status'

# Radon ergänzt normale Linux-Befehle, ersetzt sie aber nicht.
