[radon]
name=Radon OS
version=0.3.0-dev
base=linux-mint
codename=development

[design]
background=#000000
foreground=#FFFFFF
accent=#DFFF00
font=monospace

[shell]
backend=zsh
hud_key=F12

[system]
package_manager=apt
package_database=dpkg
